[package]
name = "voxflow-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-channel = "2"

[target.'cfg(target_os = "linux")'.dependencies]
global-hotkey = "0.6"
ashpd = { version = "0.10", default-features = false, features = ["tokio"] }
crossbeam-channel = "0.5"

[target.'cfg(target_os = "macos")'.dependencies]
global-hotkey = "0.6"
crossbeam-channel = "0.5"

[dev-dependencies]
tracing-subscriber.workspace = true
futures-lite = "2"
