[package]
name = "voxflow-insert"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
arboard.workspace = true
async-trait.workspace = true
enigo.workspace = true
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.10", default-features = false, features = ["tokio"] }
