[package]
name = "voxflow-linux"
version.workspace = true
edition.workspace = true

[[bin]]
name = "voxflow"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

voxflow-config.workspace = true
voxflow-core.workspace = true
voxflow-insert.workspace = true

arboard = "3"
global-hotkey = "0.6"
