// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(voxflow_ffiFFI)
import voxflow_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_voxflow_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_voxflow_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol VoxFlowEngineProtocol : AnyObject {
    
    func betaInviteValid(code: String)  -> Bool
    
    func costDashboard()  -> FfiCostDashboard
    
    func getSettings()  -> FfiSettings
    
    func listAudioDevices()  -> [String]
    
    func onHotkeyDown()  -> FfiUiState
    
    func onHotkeyUp(activeAppId: String?)  -> FfiDictationResult
    
    func prewarm() 
    
    func saveSettings(settings: FfiSettings) 
    
    func validateLicense(key: String)  -> String
    
}

open class VoxFlowEngine:
    VoxFlowEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_voxflow_ffi_fn_clone_voxflowengine(self.pointer, $0) }
    }
public convenience init(apiKey: String?) {
    let pointer =
        try! rustCall() {
    uniffi_voxflow_ffi_fn_constructor_voxflowengine_new(
        FfiConverterOptionString.lower(apiKey),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_voxflow_ffi_fn_free_voxflowengine(pointer, $0) }
    }

    

    
open func betaInviteValid(code: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_beta_invite_valid(self.uniffiClonePointer(),
        FfiConverterString.lower(code),$0
    )
})
}
    
open func costDashboard() -> FfiCostDashboard {
    return try!  FfiConverterTypeFfiCostDashboard.lift(try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_cost_dashboard(self.uniffiClonePointer(),$0
    )
})
}
    
open func getSettings() -> FfiSettings {
    return try!  FfiConverterTypeFfiSettings.lift(try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_get_settings(self.uniffiClonePointer(),$0
    )
})
}
    
open func listAudioDevices() -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_list_audio_devices(self.uniffiClonePointer(),$0
    )
})
}
    
open func onHotkeyDown() -> FfiUiState {
    return try!  FfiConverterTypeFfiUiState.lift(try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_on_hotkey_down(self.uniffiClonePointer(),$0
    )
})
}
    
open func onHotkeyUp(activeAppId: String?) -> FfiDictationResult {
    return try!  FfiConverterTypeFfiDictationResult.lift(try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_on_hotkey_up(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(activeAppId),$0
    )
})
}
    
open func prewarm() {try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_prewarm(self.uniffiClonePointer(),$0
    )
}
}
    
open func saveSettings(settings: FfiSettings) {try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_save_settings(self.uniffiClonePointer(),
        FfiConverterTypeFfiSettings.lower(settings),$0
    )
}
}
    
open func validateLicense(key: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voxflow_ffi_fn_method_voxflowengine_validate_license(self.uniffiClonePointer(),
        FfiConverterString.lower(key),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVoxFlowEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = VoxFlowEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> VoxFlowEngine {
        return VoxFlowEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: VoxFlowEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VoxFlowEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: VoxFlowEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVoxFlowEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> VoxFlowEngine {
    return try FfiConverterTypeVoxFlowEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVoxFlowEngine_lower(_ value: VoxFlowEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeVoxFlowEngine.lower(value)
}


public struct FfiCostDashboard {
    public var minutesTranscribed: Float
    public var estimatedUsd: Float
    public var estimatedInr: Float
    public var projectedMonthlyUsd: Float
    public var projectedMonthlyInr: Float
    public var localPercentage: Float
    public var cloudPercentage: Float
    public var capWarnings: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(minutesTranscribed: Float, estimatedUsd: Float, estimatedInr: Float, projectedMonthlyUsd: Float, projectedMonthlyInr: Float, localPercentage: Float, cloudPercentage: Float, capWarnings: [String]) {
        self.minutesTranscribed = minutesTranscribed
        self.estimatedUsd = estimatedUsd
        self.estimatedInr = estimatedInr
        self.projectedMonthlyUsd = projectedMonthlyUsd
        self.projectedMonthlyInr = projectedMonthlyInr
        self.localPercentage = localPercentage
        self.cloudPercentage = cloudPercentage
        self.capWarnings = capWarnings
    }
}



extension FfiCostDashboard: Equatable, Hashable {
    public static func ==(lhs: FfiCostDashboard, rhs: FfiCostDashboard) -> Bool {
        if lhs.minutesTranscribed != rhs.minutesTranscribed {
            return false
        }
        if lhs.estimatedUsd != rhs.estimatedUsd {
            return false
        }
        if lhs.estimatedInr != rhs.estimatedInr {
            return false
        }
        if lhs.projectedMonthlyUsd != rhs.projectedMonthlyUsd {
            return false
        }
        if lhs.projectedMonthlyInr != rhs.projectedMonthlyInr {
            return false
        }
        if lhs.localPercentage != rhs.localPercentage {
            return false
        }
        if lhs.cloudPercentage != rhs.cloudPercentage {
            return false
        }
        if lhs.capWarnings != rhs.capWarnings {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(minutesTranscribed)
        hasher.combine(estimatedUsd)
        hasher.combine(estimatedInr)
        hasher.combine(projectedMonthlyUsd)
        hasher.combine(projectedMonthlyInr)
        hasher.combine(localPercentage)
        hasher.combine(cloudPercentage)
        hasher.combine(capWarnings)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCostDashboard: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCostDashboard {
        return
            try FfiCostDashboard(
                minutesTranscribed: FfiConverterFloat.read(from: &buf), 
                estimatedUsd: FfiConverterFloat.read(from: &buf), 
                estimatedInr: FfiConverterFloat.read(from: &buf), 
                projectedMonthlyUsd: FfiConverterFloat.read(from: &buf), 
                projectedMonthlyInr: FfiConverterFloat.read(from: &buf), 
                localPercentage: FfiConverterFloat.read(from: &buf), 
                cloudPercentage: FfiConverterFloat.read(from: &buf), 
                capWarnings: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiCostDashboard, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.minutesTranscribed, into: &buf)
        FfiConverterFloat.write(value.estimatedUsd, into: &buf)
        FfiConverterFloat.write(value.estimatedInr, into: &buf)
        FfiConverterFloat.write(value.projectedMonthlyUsd, into: &buf)
        FfiConverterFloat.write(value.projectedMonthlyInr, into: &buf)
        FfiConverterFloat.write(value.localPercentage, into: &buf)
        FfiConverterFloat.write(value.cloudPercentage, into: &buf)
        FfiConverterSequenceString.write(value.capWarnings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCostDashboard_lift(_ buf: RustBuffer) throws -> FfiCostDashboard {
    return try FfiConverterTypeFfiCostDashboard.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCostDashboard_lower(_ value: FfiCostDashboard) -> RustBuffer {
    return FfiConverterTypeFfiCostDashboard.lower(value)
}


public struct FfiDictationResult {
    public var text: String
    public var uiState: FfiUiState
    public var latencyMs: UInt64
    public var success: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, uiState: FfiUiState, latencyMs: UInt64, success: Bool) {
        self.text = text
        self.uiState = uiState
        self.latencyMs = latencyMs
        self.success = success
    }
}



extension FfiDictationResult: Equatable, Hashable {
    public static func ==(lhs: FfiDictationResult, rhs: FfiDictationResult) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.uiState != rhs.uiState {
            return false
        }
        if lhs.latencyMs != rhs.latencyMs {
            return false
        }
        if lhs.success != rhs.success {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(uiState)
        hasher.combine(latencyMs)
        hasher.combine(success)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDictationResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDictationResult {
        return
            try FfiDictationResult(
                text: FfiConverterString.read(from: &buf), 
                uiState: FfiConverterTypeFfiUiState.read(from: &buf), 
                latencyMs: FfiConverterUInt64.read(from: &buf), 
                success: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDictationResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterTypeFfiUiState.write(value.uiState, into: &buf)
        FfiConverterUInt64.write(value.latencyMs, into: &buf)
        FfiConverterBool.write(value.success, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDictationResult_lift(_ buf: RustBuffer) throws -> FfiDictationResult {
    return try FfiConverterTypeFfiDictationResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDictationResult_lower(_ value: FfiDictationResult) -> RustBuffer {
    return FfiConverterTypeFfiDictationResult.lower(value)
}


public struct FfiSettings {
    public var qualityMode: String
    public var openaiApiKey: String?
    public var openaiModel: String
    public var microphoneDevice: String?
    public var clipboardRestore: Bool
    public var onboardingComplete: Bool
    public var isPro: Bool
    public var hotkeyKeyCode: UInt16
    public var hotkeyModifiers: UInt32
    public var hotkeyLabel: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(qualityMode: String, openaiApiKey: String?, openaiModel: String, microphoneDevice: String?, clipboardRestore: Bool, onboardingComplete: Bool, isPro: Bool, hotkeyKeyCode: UInt16, hotkeyModifiers: UInt32, hotkeyLabel: String) {
        self.qualityMode = qualityMode
        self.openaiApiKey = openaiApiKey
        self.openaiModel = openaiModel
        self.microphoneDevice = microphoneDevice
        self.clipboardRestore = clipboardRestore
        self.onboardingComplete = onboardingComplete
        self.isPro = isPro
        self.hotkeyKeyCode = hotkeyKeyCode
        self.hotkeyModifiers = hotkeyModifiers
        self.hotkeyLabel = hotkeyLabel
    }
}



extension FfiSettings: Equatable, Hashable {
    public static func ==(lhs: FfiSettings, rhs: FfiSettings) -> Bool {
        if lhs.qualityMode != rhs.qualityMode {
            return false
        }
        if lhs.openaiApiKey != rhs.openaiApiKey {
            return false
        }
        if lhs.openaiModel != rhs.openaiModel {
            return false
        }
        if lhs.microphoneDevice != rhs.microphoneDevice {
            return false
        }
        if lhs.clipboardRestore != rhs.clipboardRestore {
            return false
        }
        if lhs.onboardingComplete != rhs.onboardingComplete {
            return false
        }
        if lhs.isPro != rhs.isPro {
            return false
        }
        if lhs.hotkeyKeyCode != rhs.hotkeyKeyCode {
            return false
        }
        if lhs.hotkeyModifiers != rhs.hotkeyModifiers {
            return false
        }
        if lhs.hotkeyLabel != rhs.hotkeyLabel {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(qualityMode)
        hasher.combine(openaiApiKey)
        hasher.combine(openaiModel)
        hasher.combine(microphoneDevice)
        hasher.combine(clipboardRestore)
        hasher.combine(onboardingComplete)
        hasher.combine(isPro)
        hasher.combine(hotkeyKeyCode)
        hasher.combine(hotkeyModifiers)
        hasher.combine(hotkeyLabel)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSettings: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSettings {
        return
            try FfiSettings(
                qualityMode: FfiConverterString.read(from: &buf), 
                openaiApiKey: FfiConverterOptionString.read(from: &buf), 
                openaiModel: FfiConverterString.read(from: &buf), 
                microphoneDevice: FfiConverterOptionString.read(from: &buf), 
                clipboardRestore: FfiConverterBool.read(from: &buf), 
                onboardingComplete: FfiConverterBool.read(from: &buf), 
                isPro: FfiConverterBool.read(from: &buf), 
                hotkeyKeyCode: FfiConverterUInt16.read(from: &buf), 
                hotkeyModifiers: FfiConverterUInt32.read(from: &buf), 
                hotkeyLabel: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSettings, into buf: inout [UInt8]) {
        FfiConverterString.write(value.qualityMode, into: &buf)
        FfiConverterOptionString.write(value.openaiApiKey, into: &buf)
        FfiConverterString.write(value.openaiModel, into: &buf)
        FfiConverterOptionString.write(value.microphoneDevice, into: &buf)
        FfiConverterBool.write(value.clipboardRestore, into: &buf)
        FfiConverterBool.write(value.onboardingComplete, into: &buf)
        FfiConverterBool.write(value.isPro, into: &buf)
        FfiConverterUInt16.write(value.hotkeyKeyCode, into: &buf)
        FfiConverterUInt32.write(value.hotkeyModifiers, into: &buf)
        FfiConverterString.write(value.hotkeyLabel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSettings_lift(_ buf: RustBuffer) throws -> FfiSettings {
    return try FfiConverterTypeFfiSettings.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSettings_lower(_ value: FfiSettings) -> RustBuffer {
    return FfiConverterTypeFfiSettings.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiUiState {
    
    case idle
    case listening
    case cleaning
    case inserting
    case copied
    case done
    case error
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiUiState: FfiConverterRustBuffer {
    typealias SwiftType = FfiUiState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiUiState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .idle
        
        case 2: return .listening
        
        case 3: return .cleaning
        
        case 4: return .inserting
        
        case 5: return .copied
        
        case 6: return .done
        
        case 7: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiUiState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .idle:
            writeInt(&buf, Int32(1))
        
        
        case .listening:
            writeInt(&buf, Int32(2))
        
        
        case .cleaning:
            writeInt(&buf, Int32(3))
        
        
        case .inserting:
            writeInt(&buf, Int32(4))
        
        
        case .copied:
            writeInt(&buf, Int32(5))
        
        
        case .done:
            writeInt(&buf, Int32(6))
        
        
        case .error:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiUiState_lift(_ buf: RustBuffer) throws -> FfiUiState {
    return try FfiConverterTypeFfiUiState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiUiState_lower(_ value: FfiUiState) -> RustBuffer {
    return FfiConverterTypeFfiUiState.lower(value)
}



extension FfiUiState: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_voxflow_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_beta_invite_valid() != 17038) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_cost_dashboard() != 32017) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_get_settings() != 37261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_list_audio_devices() != 20241) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_on_hotkey_down() != 38130) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_on_hotkey_up() != 46204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_prewarm() != 40463) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_save_settings() != 52265) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_method_voxflowengine_validate_license() != 7644) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voxflow_ffi_checksum_constructor_voxflowengine_new() != 49536) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all