[package]
name = "voxflow-transcribe"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
hound = "3"
voxflow-config.workspace = true
voxflow-cost.workspace = true

[features]
default = []
local-whisper = []
